- name: Install and Build
        working-directory: ./artifacts/overlay-studio
        run: |
          npm install
          npx vite build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts/overlay-studio/dist'
